package com.hytech.model;

import java.util.Date;

public class Issue extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.id
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.status
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.title
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.creater
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.owner
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.dt_create
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private Date dtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.dt_lastupdate
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private Date dtLastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issue.content
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.id
     *
     * @return the value of Issue.id
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.id
     *
     * @param id the value for Issue.id
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.status
     *
     * @return the value of Issue.status
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.status
     *
     * @param status the value for Issue.status
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.title
     *
     * @return the value of Issue.title
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.title
     *
     * @param title the value for Issue.title
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.creater
     *
     * @return the value of Issue.creater
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.creater
     *
     * @param creater the value for Issue.creater
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.owner
     *
     * @return the value of Issue.owner
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.owner
     *
     * @param owner the value for Issue.owner
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.dt_create
     *
     * @return the value of Issue.dt_create
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public Date getDtCreate() {
        return dtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.dt_create
     *
     * @param dtCreate the value for Issue.dt_create
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setDtCreate(Date dtCreate) {
        this.dtCreate = dtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.dt_lastupdate
     *
     * @return the value of Issue.dt_lastupdate
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public Date getDtLastupdate() {
        return dtLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.dt_lastupdate
     *
     * @param dtLastupdate the value for Issue.dt_lastupdate
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setDtLastupdate(Date dtLastupdate) {
        this.dtLastupdate = dtLastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issue.content
     *
     * @return the value of Issue.content
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issue.content
     *
     * @param content the value for Issue.content
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "Issue [id=" + id + ", status=" + status + ", title=" + title
				+ ", creater=" + creater + ", owner=" + owner + ", dtCreate="
				+ dtCreate + ", dtLastupdate=" + dtLastupdate + ", content="
				+ content + "]";
	}
    
}