package com.hytech.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hytech.model.Issue;

public class IssueSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issue
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public String insertSelective(Issue record) {
        BEGIN();
        INSERT_INTO("Issue");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getCreater() != null) {
            VALUES("creater", "#{creater,jdbcType=VARCHAR}");
        }
        
        if (record.getOwner() != null) {
            VALUES("owner", "#{owner,jdbcType=VARCHAR}");
        }
        
        if (record.getDtCreate() != null) {
            VALUES("dt_create", "#{dtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDtLastupdate() != null) {
            VALUES("dt_lastupdate", "#{dtLastupdate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issue
     *
     * @mbggenerated Thu Aug 13 00:55:54 CST 2015
     */
    public String updateByPrimaryKeySelective(Issue record) {
        BEGIN();
        UPDATE("Issue");
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getCreater() != null) {
            SET("creater = #{creater,jdbcType=VARCHAR}");
        }
        
        if (record.getOwner() != null) {
            SET("owner = #{owner,jdbcType=VARCHAR}");
        }
        
        if (record.getDtCreate() != null) {
            SET("dt_create = #{dtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDtLastupdate() != null) {
            SET("dt_lastupdate = #{dtLastupdate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}